services:

  db:
    image: postgres:17
    container_name: traderoom_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: traderoom
      POSTGRES_USER: traderoom
      POSTGRES_PASSWORD: traderoom_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: traderoom_redis

    ports:
      - "6379:6379"

volumes:
  postgres_data: